### ISSUE TITLE
No Bulk and Skull theme in the comments

### ISSUE THREAD

**Issue by kameko** [webgiorno/Infornography#1]
Bug: Bulk and Skull theme not linked in the comments
How to reproduce: Read comments
Expected Result: HTTP(S) hyperlink for a video or audio recording of Bulk and Skull's theme from Mighty Morphin' Power Rangers
Actual Result: No Bulk and Skull
How to fix: https://www.youtube.com/watch?v=asPTAL5xk18

**Comment by wired-lain** [comment]
To be merged into master on the next push.
